title: [Operation RAMPART Document Library]
description: [A repository for all documents and products relating to the planning and execution of JEF missions in Op RAMPART.]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
